credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "gerrit"
          password: "123"
          scope: GLOBAL
          username: "xue.lm"
      - usernamePassword:
          id: "nexus3"
          password: "123"
          scope: GLOBAL
          username: "xuelimin"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      jenkinsUrl: "http://jenkins.kubernetes-plugin:8080"
      maxRequestsPerHost: 32
      maxRequestsPerHostStr: "32"
      name: "kubernetes"
      serverUrl: "https://kubernetes.default"
      skipTlsVerify: true
      templates:
      - containers:
        - args: "cat"
          command: "/bin/sh -c"
          image: "jenkins/jnlp-slave:latest"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jenkins-slave"
          resourceLimitCpu: "8"
          resourceLimitMemory: "10Gi"
          resourceRequestCpu: "6"
          resourceRequestMemory: "8Gi"
          ttyEnabled: true
          workingDir: "/home/jenkins/agent"
        hostNetwork: false
        label: "jenkins-slave"
        name: "jenkins-slave"
        nodeSelector: "android_compile: compile_env"
        nodeUsageMode: NORMAL
        yamlMergeStrategy: "override"
      - containers:
        - args: "cat"
          command: "/bin/bash -c"
          image: "qingfeng1987/ubuntu_android:1.4"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "ubuntu-compile"
          resourceLimitCpu: "8"
          resourceLimitMemory: "10Gi"
          resourceRequestCpu: "6"
          resourceRequestMemory: "8Gi"
          ttyEnabled: true
          workingDir: "/home/jenkins/agent"
        hostNetwork: false
        label: "compile_env"
        name: "ubuntu-compile"
        nodeSelector: "android_compile: compile_env"
        nodeUsageMode: NORMAL
        volumes:
        - hostPathVolume:
            hostPath: "/home/jenkins/agent"
            mountPath: "/home/jenkins/agent"
        yamlMergeStrategy: "override"
