credentials:
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "6416b644-72ba-47b5-b04a-381b659d662e"
          password: "{AQAAABAAAAAQanmmmFVmNpUmUj29Ah8Yo4gGLWX6havFWHTYdiOSFVs=}"
          scope: GLOBAL
          username: "gerritadmin"
      - usernamePassword:
          id: "575c5290-67c7-4751-93d9-33d2289d4bd8"
          password: "{AQAAABAAAAAwmvlQW07JvJs0zkPQgAV6/6bsh91HMCgSKD4JYKVBnrN3xsFpvfRmMxPisGSS+Ru66WBasrNsE8XNwXx59qucWA==}"
          scope: GLOBAL
          username: "admin"
      - string:
          id: "2436e5bb-4d58-4c5b-b061-37ebad70af62"
          scope: GLOBAL
          secret: "{AQAAABAAAAAwKbZkrHCD86sXhL4SdC74NtoflglxRTxYQMF3H228lEIMcrvgug9CK8hOOwjQCdT/l6Hcf9DFL75Zu/Xn8PdNLA==}"
jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - assignments:
          - "liu-dj"
          - "li_qf"
          - "xuelm"
          name: "admin"
          pattern: ".*"
          permissions:
          - "Job/Move"
          - "Job/Build"
          - "Lockable Resources/View"
          - "Credentials/Delete"
          - "Credentials/ManageDomains"
          - "Lockable Resources/Unlock"
          - "View/Create"
          - "Agent/Configure"
          - "Job/Read"
          - "Credentials/Update"
          - "Agent/Create"
          - "Job/ExtendedRead"
          - "Overall/SystemRead"
          - "Manage ownership/Nodes"
          - "Job/Delete"
          - "Agent/Build"
          - "View/Configure"
          - "Lockable Resources/Reserve"
          - "Agent/Provision"
          - "SCM/Tag"
          - "Job/Create"
          - "Job/Discover"
          - "Manage ownership/Jobs"
          - "Agent/ExtendedRead"
          - "Credentials/View"
          - "Agent/Connect"
          - "Agent/Delete"
          - "Gerrit/Retrigger"
          - "Run/Replay"
          - "Agent/Disconnect"
          - "Run/Delete"
          - "Job/Cancel"
          - "Overall/Read"
          - "Run/Update"
          - "Credentials/Create"
          - "Overall/Administer"
          - "Gerrit/ManualTrigger"
          - "View/Delete"
          - "Job/Configure"
          - "Job/Workspace"
          - "View/Read"
        - assignments:
          - "fuyongjie"
          - "lujuntuan"
          - "lijiancheng"
          - "liuxiting"
          - "tianyu"
          - "chenjide"
          - "liwei"
          - "xuelimin"
          name: "normal user"
          pattern: ".*"
          permissions:
          - "Job/Cancel"
          - "Overall/Read"
          - "Job/Build"
          - "Gerrit/ManualTrigger"
          - "Job/Read"
          - "View/Read"
  clouds:
  - kubernetes:
      containerCap: 10
      containerCapStr: "10"
      jenkinsUrl: "http://jenkins.kubernetes-plugin:8080"
      maxRequestsPerHost: 32
      maxRequestsPerHostStr: "32"
      name: "kubernetes"
      serverUrl: "https://kubernetes.default"
      skipTlsVerify: true
      templates:
      - containers:
        - args: "cat"
          command: "/bin/sh -c"
          image: "jenkins/jnlp-slave:4.0.1-1"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "jenkins-slave"
          resourceLimitCpu: "8"
          resourceLimitMemory: "10Gi"
          resourceRequestCpu: "6"
          resourceRequestMemory: "8Gi"
          ttyEnabled: true
          workingDir: "/home/jenkins/agent"
        hostNetwork: false
        label: "jenkins-slave"
        name: "jenkins-slave"
        nodeSelector: "android_compile: compile_env"
        nodeUsageMode: NORMAL
        yamlMergeStrategy: "override"
      - containers:
        - args: "cat"
          command: "/bin/bash -c"
          image: "qingfeng1987/ubuntu_android:1.9"
          livenessProbe:
            failureThreshold: 0
            initialDelaySeconds: 0
            periodSeconds: 0
            successThreshold: 0
            timeoutSeconds: 0
          name: "ubuntu-compile"
          resourceLimitCpu: "8"
          resourceLimitMemory: "10Gi"
          resourceRequestCpu: "6"
          resourceRequestMemory: "8Gi"
          ttyEnabled: true
          workingDir: "/home/jenkins/agent"
        hostNetwork: false
        label: "ubuntu-compile"
        name: "ubuntu-compile"
        nodeSelector: "android_compile: compile_env"
        nodeUsageMode: NORMAL
        volumes:
        - hostPathVolume:
            hostPath: "/home/jenkins/agent"
            mountPath: "/home/jenkins/agent"
        yamlMergeStrategy: "override"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  globalNodeProperties:
  - envVars:
      env:
      - key: "PATH"
        value: "/usr/local/openjdk-8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/sonar-scanner/bin"
  labelAtoms:
  - name: "jenkins-slave"
  - name: "master"
  - name: "ubuntu-compile"
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  proxy:
    name: "proxy.neusoft.com"
    noProxyHost: "10.1.23.*, *.coc-automative.com"
    port: 8080
    secretPassword: "{AQAAABAAAAAQb69OlZ2pVTMeInIkiqJtWJp3DMgys44enTDCTwzWets=}"
    testUrl: "https://www.baidu.com"
    userName: "li_qf"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: true
      enableCaptcha: false
      users:
      - id: "chenjide"
        name: "chenjinda"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "chenjide@neusoft.com"
        - "user"
      - id: "fuyongjie"
        name: "fuyongjie"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "fuyongjie@neusoft.com"
        - "user"
      - id: "li_qf"
        name: "liqingfeng"
        properties:
        - "apiToken"
        - mailer:
            emailAddress: "li_qf@neusoft.com"
        - preferredProvider:
            providerId: "default"
        - "user"
      - id: "lijiancheng"
        name: "lijiancheng"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "lijiancheng@neusoft.com"
        - "user"
      - id: "liu-dj"
        name: "liudejun"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "liu-dj@neusoft.com"
        - "user"
      - id: "liuxiting"
        name: "liuxiting"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "liu.xiting@neusoft.com"
        - "user"
      - id: "liwei"
        name: "liwei"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "li_wei_neu@neusoft.com"
        - "user"
      - id: "lujuntuan"
        name: "lujuntuan"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "lujuntuan@neusoft.com"
        - "user"
      - id: "tianyu"
        name: "tianyu"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "tian.yu@neusoft.com"
        - "user"
      - id: "xuelimin"
        name: "xuelimin"
        properties:
        - "apiToken"
        - "myView"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - mailer:
            emailAddress: "xue.lm@neusoft.com"
        - "user"
      - id: "xuelm"
        name: "xuelm"
        properties:
        - "apiToken"
        - mailer:
            emailAddress: "xue.lm@neusoft.com"
        - preferredProvider:
            providerId: "default"
        - "user"
        - ? ''
          : authorizedKeys: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfy3vRrAP0kVpvZS9J7N5YJYge3tXujaWybXrWeA0dxL+znwHD1wetD3OQHiiFIMeW7a1ZNKuRRlf/XF/2dIFBQhj4GveNSLDRK9tWI3uOomdbqh6C+fUbFjCrep4qU2mTHUes6Vt3A2Z8RAmQLi+GxNusaTuh5xBr5PUOAiZrxSjGuLpwXAga5IrcGzjTrDCwj/P4QbBVxzKkrs1P/aP5X6kIKhR5gwsjRVmz5HujcPZf5zeAANFGeg+zFd4VDOAlnmkLievAPqlRQ16o8Wf8GSJbjozUtQv3gInsDU3brlQ0bdMjEdNVoQIp2u/m/U1S6UMpjutvD4Ms3e0jNtmD\
              \ xue@coc-xue"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      jobNames:
      - "C4pro_Nightly_Build"
      - "C4pro_Release_Build"
      - "C4pro_Verify_Build"
      - "env_test"
      name: "C4pro"
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      jobNames:
      - "Qcom_android_Verify_Build"
      - "Qcom_Nightly_Build"
      - "Qcom_qnx_Verify_Build"
      - "Qcom_Release_Build"
      name: "QNX-project"
  - all:
      name: "all"
  - list:
      columns:
      - "status"
      - "weather"
      - "jobName"
      - "lastSuccess"
      - "lastFailure"
      - "lastDuration"
      - "buildButton"
      jobNames:
      - "Android_Verify_test"
      - "liqingfeng_test"
      - "liqingfeng_test2"
      - "Nightly_Build_test"
      - "QCOM_Release_test"
      - "Qnx_Verify_test"
      - "release-job"
      - "sonarqube-test"
      - "test"
      - "test-job"
      name: "test_view"
  viewsTabBar: "standard"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  envInject:
    enableLoadingFromMaster: false
    enablePermissions: false
    hideInjectedVars: false
  sSHD:
    port: -1
unclassified:
  ansiColorBuildWrapper:
    colorMaps:
    - black: "#000000"
      blackB: "#4C4C4C"
      blue: "#1E90FF"
      blueB: "#4682B4"
      cyan: "#00CDCD"
      cyanB: "#00FFFF"
      green: "#00CD00"
      greenB: "#00FF00"
      magenta: "#CD00CD"
      magentaB: "#FF00FF"
      name: "xterm"
      red: "#CD0000"
      redB: "#FF0000"
      white: "#E5E5E5"
      whiteB: "#FFFFFF"
      yellow: "#CDCD00"
      yellowB: "#FFFF00"
    - black: "#000000"
      blackB: "#555555"
      blue: "#0000AA"
      blueB: "#5555FF"
      cyan: "#00AAAA"
      cyanB: "#55FFFF"
      defaultBackground: 0
      defaultForeground: 7
      green: "#00AA00"
      greenB: "#55FF55"
      magenta: "#AA00AA"
      magentaB: "#FF55FF"
      name: "vga"
      red: "#AA0000"
      redB: "#FF5555"
      white: "#AAAAAA"
      whiteB: "#FFFFFF"
      yellow: "#AA5500"
      yellowB: "#FFFF55"
    - black: "black"
      blackB: "black"
      blue: "blue"
      blueB: "blue"
      cyan: "cyan"
      cyanB: "cyan"
      green: "green"
      greenB: "green"
      magenta: "magenta"
      magentaB: "magenta"
      name: "css"
      red: "red"
      redB: "red"
      white: "white"
      whiteB: "white"
      yellow: "yellow"
      yellowB: "yellow"
    - black: "#2E3436"
      blackB: "#2E3436"
      blue: "#3465A4"
      blueB: "#3465A4"
      cyan: "#06989A"
      cyanB: "#06989A"
      defaultBackground: 0
      defaultForeground: 7
      green: "#4E9A06"
      greenB: "#4E9A06"
      magenta: "#75507B"
      magentaB: "#75507B"
      name: "gnome-terminal"
      red: "#CC0000"
      redB: "#CC0000"
      white: "#D3D7CF"
      whiteB: "#D3D7CF"
      yellow: "#C4A000"
      yellowB: "#C4A000"
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  defaultFolderConfiguration:
    healthMetrics:
    - worstChildHealthMetric:
        recursive: true
  extendedEmailPublisher:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:\r\n\r\nCheck\
      \ console output at $BUILD_URL to view the results."
    defaultContentType: "text/html"
    defaultRecipients: "xue.lm@nuesoft.com"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultSuffix: "@neusoft.com"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: 0
    precedenceBulk: false
    smtpPassword: "{AQAAABAAAAAQrBrs9gWb7f28mXvdfCnq8riMCXdn4N7xclTqMz9AOlE=}"
    smtpPort: "587"
    smtpServer: "smtp.neusoft.com"
    smtpUsername: "xue.lm"
    useSsl: false
    watchingEnabled: false
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://jenkins.coc-automative.com/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
    globalConfigEmail: "coc_android@neusoft.com"
    globalConfigName: "coc_android"
    showEntireCommitSummaryInChanges: true
    useExistingAccountWithSameEmail: false
  globalNexusConfiguration:
    instanceId: "1b4801d093d040c681f74122bd7457d4"
  groovyScriptMES:
    secureOnly: false
  location:
    adminAddress: "xue.lm@neusoft.com"
    url: "http://jenkins.coc-automative.com/"
  mailer:
    authentication:
      password: "{AQAAABAAAAAQ4xFzDyoribH3P75AVzZZFYQKwiMHCW/8gZ3hgbpYPQc=}"
      username: "xue.lm"
    charset: "UTF-8"
    defaultSuffix: "@neusoft.com"
    smtpHost: "smtp.neusoft.com"
    smtpPort: "587"
    useSsl: false
    useTls: true
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  sonarGlobalConfiguration:
    buildWrapperEnabled: true
    installations:
    - credentialsId: "2436e5bb-4d58-4c5b-b061-37ebad70af62"
      name: "MySonarQube"
      serverUrl: "http://10.1.23.67:9000"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
    - triggers:
        skipScmCause: false
        skipUpstreamCause: false
tool:
  cmakeTool:
    installations:
    - name: "InSearchPath"
  git:
    installations:
    - home: "/usr/bin/git"
      name: "Default"
  sonarRunnerInstallation:
    installations:
    - name: "MySonarQube"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "4.4.0.2170"
